# permissions for end users to edit standbydatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: standbydatabase-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - standbydatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - standbydatabases/status
  verbs:
  - get
