name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Golang setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
        
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        env:
          BRANCH_NAME: ${GITHUB_REF#refs/heads/}

      # extract branch name on pull request
      - name: Extract branch name
        if: github.event_name == 'pull_request'
        env:
          BRANCH_NAME: ${GITHUB_HEAD_REF}

      # Build and push Operator image (don't push on PR)
      - name: Build and push Docker image
        run:  |
          make generate
          make manifests
          IMAGE_NAME=${{ env.IMAGE }}
          IMAGE_NAME=${IMAGE,,}
          make docker-build IMG="${{ env.REGISTRY }}/${IMAGE_NAME}:${BRANCH_NAME}"
          docker push "${{ env.REGISTRY }}/${IMAGE_NAME}:${BRANCH_NAME}"
          docker rmi "${{ env.REGISTRY }}/${IMAGE_NAME}:${BRANCH_NAME}" && docker system prune -f
          rm -rf bin/
